[package]
name = "voice-ja"
description = "Japanese voice module for Nmemonica"
version = "0.1.0"
authors = ["bryanjimenez <bryanjimenez6@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# wee_alloc
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.92"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
cfg-if = "1.0.0"

jbonsai = { version = "0.1.1", features = ["htsvoice"] }
jpreprocess = { version = "0.9.1", features = ["naist-jdic"] }
rodio = "0.19.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"


[lints.clippy]
unwrap_used = "deny"