on: workflow_call
permissions: {}

jobs:
  test-pkg:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #actions/checkout@v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #actions/download-artifact@v8
        with:
          name: pkg
          path: pkg

      - name: current version for test dependency
        run: node ./pkg_helper.js test-update

      - run: npm --prefix ./tests install

      - run: npm run --prefix ./tests test
