on: workflow_call
permissions: {}

jobs:
  check-tag:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #actions/checkout@v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #actions/download-artifact@v8
        with:
          name: pkg
      - name: Verify tag version
        run: |
            echo "tag_ref: $GITHUB_REF_NAME"
            pkg_ver=`grep version ./package.json | sed -r -e's/(version)|[",: ]//g' -e 's/^/v/g'`
            echo "pkg_ver: $pkg_ver"
            [[ "$pkg_ver" != "$GITHUB_REF_NAME" ]] && echo "::warning:: $GITHUB_REF_NAME != $pkg_ver"
            [[ "$pkg_ver" == "$GITHUB_REF_NAME" ]]
