on: workflow_call

jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: install-wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: build-pkg
        run: wasm-pack build --scope nmemonica --release

      - name: bundle third party notices
        run: |
          echo "THIRD PARTY SOFTWARE NOTICES AND INFORMATION" > ./pkg/ThirdPartyNotice.txt
          echo "Do Not Translate or Localize" >> ./pkg/ThirdPartyNotice.txt
          echo "\n--------------------------------------------------------------------------------" >> ./pkg/ThirdPartyNotice.txt
          echo "htsvoice-tohoku-f01 v8e33060 - 2015 Intelligent Communication Network (Ito-Nose) Laboratory, Tohoku University" >> ./pkg/ThirdPartyNotice.txt
          echo "https://github.com/icn-lab/htsvoice-tohoku-f01" >> ./pkg/ThirdPartyNotice.txt
          echo "--------------------------------------------------------------------------------\n" >> ./pkg/ThirdPartyNotice.txt
          cat ./htsvoice/tohoku-f01/COPYRIGHT.txt >> ./pkg/ThirdPartyNotice.txt

      - name: pack-pkg
        run: wasm-pack pack

      - uses: actions/upload-artifact@v7
        with:
          name: pkg
          path: pkg/
