on: workflow_call

jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: install cargo-audit
        run: |
          cargo install cargo-audit cargo-license wasm-pack
          cargo audit

      - name: build-pkg
        run: wasm-pack build --scope nmemonica --release

      - name: package third-party-notice
        run: node ./pkg_helper.js third-party

      - name: pack-pkg
        run: wasm-pack pack

      - uses: actions/upload-artifact@v7
        with:
          name: pkg
          path: pkg/
