name: Test pkg
on: workflow_call

jobs:
  test-pkg:
    environment: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@v6
        with:
          name: pkg
          path: pkg

      - run: npm --prefix ./tests install

      - run: npm run --prefix ./tests test
