name: Publish to npmjs
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/job-build.yml

  test-pkg:
    needs: build
    uses: ./.github/workflows/job-test.yml

  publish-npm:
    needs: test-pkg
    uses: ./.github/workflows/job-publish.yml
