name: Pull Request
permissions: {}

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/job-build.yml

  test-pkg:
    needs: build
    uses: ./.github/workflows/job-test.yml
